### ISSUE TITLE
generateChangelog does not generate * for commits for MarkDown

### ISSUE THREAD

**Issue by thatsIch** [selesse/gradle-git-changelog#1]
In a prior version the commits had a pre \* for making it a md list.
This feature is gone in 0.1.2. HTML is working fine with the template engine

**Comment by selesse** [comment]
Would you be able to solve this problem by specifying a commitFormat, like this?

```
changelog {
    commitFormat = '* %s (%an)' 
}
```

One disadvantage to this approach is that your HTML markup will include unnecessary `*`s, like this: 

<img width="446" alt="Gradle Git Changelog" src="https://cloud.githubusercontent.com/assets/563658/10411340/7ebc092c-6f2f-11e5-8f80-ae579ad6cadf.png">

 Perhaps I should include `markdownCommitFormat` and `htmlCommitFormat` options? What do you think?

**Comment by thatsIch** [comment]
I solved it by adding a double space, which acts as a return. 

```
input + "  "
```

I think using two templates or two processors would be fine, but default should be that \* is being added to the MD to be on par with HTML

**Comment by selesse** [comment]
Agreed! I will push a fix soon. Thanks. :)

**Comment by thatsIch** [comment]
Cheers :+1:
