### ISSUE TITLE
I tried to use the standard example configuration , and it doesn't work

### ISSUE THREAD

**Issue by joychugh** [selesse/gradle-git-changelog#5]
`changelog {
    // The title appears at the top of the changelog.
    // Default value: the name of the project.
    title = "${project.name} - Changelog"

```
// The output directory where the report is generated.
// Default value: main resource directory, or the "build" directory
outputDirectory = file("$projectDir")

// The name of the report to generate.
// Default value: CHANGELOG.md
fileName = "changelog.txt"

// The range of commits the changelog should be composed of.
// Default value: 'beginning' (i.e. full changelog)
// Possible values: 'beginning', 'last_tag', 'xxx'
//
// 'last_tag' will use all the commits since the last tag,
// 'beginning' will use all commits since the initial commit (default)
// 'xxx' will use all the tags since the 'xxx' Git reference (i.e. `since = 1.2.0` will display the changelog
//       since the 1.2.0 tag, excluding 1.2.0)

// The output formats that should be generated.
// Default value: ['markdown']
// Possible values: 'html', 'markdown'.
formats = ['html', 'markdown']


// The Git "pretty" changelog commit format.
// Default value: %ad%x09%s (%an), which produces:
// Thu May 7 20:10:33 2015 -0400    Initial commit (Alex Selesse)
commitFormat = '%s (%an)'

// Specifies a commit format for Markdown.
// Default value: '* %s (%an)', which produces:
// * Initial commit (Alex Selesse)
markdown {
    commitFormat = '* %s (%an)'
}

// Specifies a commit format for the HTML template.
// Default value: see commitFormat
html {
    commitFormat = '%s (%an)'

    // The Groovy HTML template used to generate the HTML changelog.
    // See http://docs.groovy-lang.org/latest/html/documentation/template-engines.html
    template = file("$projectDir/htmlTemplate").text
}
```

//    // A closure that returns 'true' if the line should be included in the changelog.
//    // Default value: accept everything, { true }
//    includeLines = {
//        !it.contains("Merge")
//    }
//
//    // A closure that transforms a changelog String.
//    // Default value: the identity closure, { it }
//    //
//    // For example, to remove '[ci skip]' from the changelog messages:
//    processLines = {
//        String input = it as String
//        if (input.contains('[ci skip] ')) {
//            input = input.minus('[ci skip] ')
//        }
//        input
//    }
}
`
My configuration for the plugin but it doesn't generate anything

`jchugh:test jchugh$ ./gradlew --version

---
## Gradle 2.2

Build time:   2014-11-10 13:31:44 UTC
Build number: none
Revision:     aab8521f1fd9a3484cac18123a72bcfdeb7006ec

Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Mac OS X 10.11.4 x86_64`

I have added the plugins to my build.gradle

**Comment by selesse** [comment]
Hi!

The example configuration shows all of the _optional_ parameters that you can configure `gradle-git-changelog` with. If you copy/paste the one from [the readme](https://github.com/selesse/gradle-git-changelog/blob/master/README.md), it won't work because it assumes that a file called `htmlTemplate` exists. Have you tried just adding the following snippet to your Gradle project:

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.selesse:gradle-git-changelog:0.2.0'
    }
}

apply plugin: 'com.selesse.git.changelog'
```

This should work without any modifications. If it doesn't, can you provide me the error that you get when you try to `./gradlew assemble`? :)
