### ISSUE TITLE
outputDirectory variable can't be setted.

### ISSUE THREAD

**Issue by urosjarc** [selesse/gradle-git-changelog#6]
This is build settings:

```
changelog {
    title = "${project.name}"
    outputDirectory = file("$projectDir/docs/src")
    fileName = "changes.md"
    //since = 'last_tag'
    formats = ['markdown']
    commitFormat = '%ad%x09%s (%an)'
    println(outputDirectory)
}
```

And this is debug line:

```
14:19:45.846 [DEBUG] [com.selesse.gradle.git.changelog.GitLogPlugin] Setting destination directory to /home/urosjarc/Downloads/testGenerator/build/resources/main
```

And here is all debug stack: [debug.txt](https://github.com/selesse/gradle-git-changelog/files/418023/debug.txt)

**Comment by selesse** [comment]
Hi.

Thanks for the bug report. This is an issue that only affects Java projects. I'm working on a fix.

**Comment by urosjarc** [comment]
Thank you for quick response, this is really appreciated! Oh and would you be so kind to update the version in https://plugins.gradle.org/. :+1:
